baseURL = 'https://gorodri.dev/'
languageCode = 'en-us'
title = 'GoRodri'
theme = 'PaperMod'

[params]
  description = "A blog by Rodrigo Tavares, covering a wide range of topics from Linux Containers and Kubernetes to politics, economy, and philosophy. Opinions are my own."
  author = "Rodrigo Tavares"
  keywords = ["Kubernetes", "OpenShift", "Linux Containers", "Podman"]
  favicon = "images/favicon.ico"

  [params.mainSections]
    section1 = "post"
    section2 = "projects"

  [params.homeInfoParams]
    Title = "Hello :)"
    Content = "Welcome to my blog. Here you will find cool information about the Linux Containers world such as Podman, Kubernetes, and OpenShift."

  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/RodrigoCTavares"
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/tavaresrodrigo"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Posts"
    url = "/post/"
    weight = 2
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4